// Tamiya paint reference colors (approximate digital hex values).
// These are practical screen-color approximations, not official spectrophotometer/Lab measurements.
// X/XF are the most complete here; LP/TS are expanded reference selections for matching/filtering.
export interface TamiyaColor {
  code: string;
  name: string;
  hex: string;
}

export const TAMIYA_COLORS: TamiyaColor[] = [
  { code: "X-1", name: "Black", hex: "#0a0a0a" },
  { code: "X-2", name: "White", hex: "#ffffff" },
  { code: "X-3", name: "Royal Blue", hex: "#003a8c" },
  { code: "X-4", name: "Blue", hex: "#0055a4" },
  { code: "X-5", name: "Green", hex: "#0a7a3b" },
  { code: "X-6", name: "Orange", hex: "#f26522" },
  { code: "X-7", name: "Red", hex: "#c8102e" },
  { code: "X-8", name: "Lemon Yellow", hex: "#f7d417" },
  { code: "X-9", name: "Brown", hex: "#5a2d0c" },
  { code: "X-11", name: "Chrome Silver", hex: "#c0c0c0" },
  { code: "X-12", name: "Gold Leaf", hex: "#d4af37" },
  { code: "X-13", name: "Metallic Blue", hex: "#1f4e79" },
  { code: "X-14", name: "Sky Blue", hex: "#3aa9e0" },
  { code: "X-15", name: "Light Green", hex: "#7ac74f" },
  { code: "X-16", name: "Purple", hex: "#6a1b9a" },
  { code: "X-17", name: "Pink", hex: "#e91e63" },
  { code: "X-18", name: "Semi Gloss Black", hex: "#1a1a1a" },
  { code: "X-19", name: "Smoke", hex: "#3b2f2f" },
  { code: "X-20", name: "Clear", hex: "#eeeeee" },
  { code: "X-21", name: "Flat Base", hex: "#f5f5f5" },
  { code: "X-22", name: "Clear", hex: "#f0f0f0" },
  { code: "X-24", name: "Clear Yellow", hex: "#fff08a" },
  { code: "X-25", name: "Clear Green", hex: "#8ce08c" },
  { code: "X-26", name: "Clear Orange", hex: "#ffb066" },
  { code: "X-27", name: "Clear Red", hex: "#ff5060" },
  { code: "X-28", name: "Park Green", hex: "#2f5233" },
  { code: "X-31", name: "Titanium Gold", hex: "#b08d3c" },
  { code: "X-32", name: "Titanium Silver", hex: "#b8b8b8" },
  { code: "X-33", name: "Bronze", hex: "#8c6b2f" },
  { code: "X-34", name: "Metallic Brown", hex: "#6b3a17" },
  { code: "XF-1", name: "Flat Black", hex: "#141414" },
  { code: "XF-2", name: "Flat White", hex: "#f2f2f2" },
  { code: "XF-3", name: "Flat Yellow", hex: "#f2c200" },
  { code: "XF-4", name: "Yellow Green", hex: "#b9c46a" },
  { code: "XF-5", name: "Flat Green", hex: "#2f6b2f" },
  { code: "XF-6", name: "Copper", hex: "#b87333" },
  { code: "XF-7", name: "Flat Red", hex: "#a5261b" },
  { code: "XF-8", name: "Flat Blue", hex: "#1f3a68" },
  { code: "XF-9", name: "Hull Red", hex: "#5a1e1a" },
  { code: "XF-10", name: "Flat Brown", hex: "#4b2e1d" },
  { code: "XF-11", name: "J.N. Green", hex: "#374b31" },
  { code: "XF-12", name: "J.N. Grey", hex: "#8a99a1" },
  { code: "XF-13", name: "J.A. Green", hex: "#4b5a2a" },
  { code: "XF-14", name: "J.A. Grey", hex: "#8a8a76" },
  { code: "XF-15", name: "Flat Flesh", hex: "#e6bfa1" },
  { code: "XF-16", name: "Flat Aluminum", hex: "#a8a8a8" },
  { code: "XF-17", name: "Sea Blue", hex: "#1c3a5e" },
  { code: "XF-18", name: "Medium Blue", hex: "#26588a" },
  { code: "XF-19", name: "Sky Grey", hex: "#b5bbbd" },
  { code: "XF-20", name: "Medium Grey", hex: "#8f9296" },
  { code: "XF-21", name: "Sky", hex: "#a8b98a" },
  { code: "XF-22", name: "RLM Grey", hex: "#7a7d6e" },
  { code: "XF-23", name: "Light Blue", hex: "#7ea7c8" },
  { code: "XF-24", name: "Dark Grey", hex: "#4c4f52" },
  { code: "XF-25", name: "Light Sea Grey", hex: "#9aa1a3" },
  { code: "XF-26", name: "Deep Green", hex: "#1f3a26" },
  { code: "XF-27", name: "Black Green", hex: "#22301f" },
  { code: "XF-49", name: "Khaki", hex: "#7a6b3f" },
  { code: "XF-50", name: "Field Blue", hex: "#3c556e" },
  { code: "XF-51", name: "Khaki Drab", hex: "#6b5b3a" },
  { code: "XF-52", name: "Flat Earth", hex: "#7a5230" },
  { code: "XF-53", name: "Neutral Grey", hex: "#6f7378" },
  { code: "XF-54", name: "Dark Sea Grey", hex: "#5c6469" },
  { code: "XF-55", name: "Deck Tan", hex: "#c9b48a" },
  { code: "XF-56", name: "Metallic Grey", hex: "#7d8388" },
  { code: "XF-57", name: "Buff", hex: "#c2a878" },
  { code: "XF-58", name: "Olive Green", hex: "#4b5a2e" },
  { code: "XF-59", name: "Desert Yellow", hex: "#c9a86b" },
  { code: "XF-60", name: "Dark Yellow", hex: "#b8963f" },
  { code: "XF-61", name: "Dark Green", hex: "#2f4a2a" },
  { code: "XF-62", name: "Olive Drab", hex: "#4a4a2a" },
  { code: "XF-63", name: "German Grey", hex: "#3a3f42" },
  { code: "XF-64", name: "Red Brown", hex: "#6b2f22" },
  { code: "XF-65", name: "Field Grey", hex: "#5c5a45" },
  { code: "XF-66", name: "Light Grey", hex: "#9c9c9c" },
  { code: "XF-67", name: "NATO Green", hex: "#3a4a2f" },
  { code: "XF-68", name: "NATO Brown", hex: "#4a3524" },
  { code: "XF-69", name: "NATO Black", hex: "#1f1f1f" },
  { code: "XF-70", name: "Dark Green 2", hex: "#2a3f2a" },
  { code: "XF-71", name: "Cockpit Green", hex: "#3f5a3a" },
  { code: "XF-72", name: "Brown (JGSDF)", hex: "#5a3a24" },
  { code: "XF-73", name: "Dark Green (JGSDF)", hex: "#2f4030" },
  { code: "XF-74", name: "Olive Drab (JGSDF)", hex: "#524a2e" },
  { code: "XF-75", name: "IJN Grey", hex: "#6b7075" },
  { code: "XF-76", name: "IJN Grey Green", hex: "#7a7a5f" },
  { code: "XF-77", name: "IJN Grey (Sasebo)", hex: "#7a7d80" },
  { code: "XF-78", name: "Wooden Deck Tan", hex: "#b89566" },
  { code: "XF-79", name: "Linoleum Deck Brown", hex: "#5a3a24" },
  { code: "XF-80", name: "Royal Light Grey", hex: "#a5abaa" },
  { code: "XF-81", name: "Dark Green 2 RAF", hex: "#2f4230" },
  { code: "XF-82", name: "Ocean Grey RAF", hex: "#6a7278" },
  { code: "XF-83", name: "Medium Sea Grey RAF", hex: "#8c9295" },
  { code: "XF-84", name: "Dark Iron", hex: "#3a3a3a" },
  { code: "XF-85", name: "Rubber Black", hex: "#1a1a1a" },
  { code: "XF-86", name: "Flat Clear", hex: "#e8e8e8" },

  { code: "LP-1", name: "Black", hex: "#141414" },
  { code: "LP-2", name: "White", hex: "#f2f0e8" },
  { code: "LP-3", name: "Flat Black", hex: "#1b1b1b" },
  { code: "LP-4", name: "Flat White", hex: "#e9e7df" },
  { code: "LP-5", name: "Semi Gloss Black", hex: "#242526" },
  { code: "LP-6", name: "Pure Blue", hex: "#214f9a" },
  { code: "LP-7", name: "Pure Red", hex: "#b5232d" },
  { code: "LP-8", name: "Pure Yellow", hex: "#e3c82e" },
  { code: "LP-11", name: "Silver", hex: "#aeb3b6" },
  { code: "LP-18", name: "Dull Red", hex: "#8e3c3f" },
  { code: "LP-19", name: "Gun Metal", hex: "#555a5d" },
  { code: "LP-20", name: "Light Gun Metal", hex: "#777b7e" },
  { code: "LP-21", name: "Italian Red", hex: "#b12f31" },
  { code: "LP-23", name: "Flat Clear", hex: "#d5d5ce" },
  { code: "LP-25", name: "Brown", hex: "#674630" },
  { code: "LP-26", name: "Dark Green", hex: "#334835" },
  { code: "LP-27", name: "German Grey", hex: "#44484a" },
  { code: "LP-28", name: "Olive Drab", hex: "#57583e" },
  { code: "LP-29", name: "Olive Drab 2", hex: "#626348" },
  { code: "LP-30", name: "Light Sand", hex: "#c2ad77" },
  { code: "LP-31", name: "Dark Green 2", hex: "#41523e" },
  { code: "LP-32", name: "Light Grey", hex: "#a6a8a3" },
  { code: "LP-33", name: "Grey Green", hex: "#788579" },
  { code: "LP-34", name: "Light Grey Green", hex: "#9aa59a" },
  { code: "LP-35", name: "Insignia White", hex: "#e2dfd3" },
  { code: "LP-36", name: "Dark Ghost Gray", hex: "#7c8281" },
  { code: "LP-37", name: "Light Ghost Gray", hex: "#a4aaa8" },
  { code: "LP-38", name: "Flat Aluminum", hex: "#9ca1a2" },
  { code: "LP-39", name: "Racing White", hex: "#e6e1d4" },
  { code: "LP-40", name: "Metallic Black", hex: "#303234" },
  { code: "LP-41", name: "Mica Blue", hex: "#28507f" },
  { code: "LP-42", name: "Mica Red", hex: "#832d34" },
  { code: "LP-43", name: "Pearl White", hex: "#e8e7de" },
  { code: "LP-45", name: "Racing Blue", hex: "#274f82" },
  { code: "LP-49", name: "Bright Red", hex: "#c33236" },
  { code: "LP-50", name: "Bright Blue", hex: "#3563a0" },
  { code: "LP-51", name: "Pure Orange", hex: "#e07825" },
  { code: "LP-54", name: "Dark Iron", hex: "#4a4b49" },
  { code: "LP-55", name: "Dark Yellow 2", hex: "#9b8348" },
  { code: "LP-56", name: "Dark Green 2", hex: "#3d4938" },
  { code: "LP-57", name: "Red Brown 2", hex: "#69443a" },
  { code: "LP-58", name: "NATO Green", hex: "#4d5941" },
  { code: "LP-59", name: "NATO Brown", hex: "#5a4338" },
  { code: "LP-60", name: "NATO Black", hex: "#292d2c" },
  { code: "LP-61", name: "Metallic Gray", hex: "#707374" },
  { code: "LP-62", name: "Titanium Gold", hex: "#a48c5a" },
  { code: "LP-63", name: "Titanium Silver", hex: "#a6a29b" },
  { code: "LP-64", name: "Olive Drab", hex: "#5a5a40" },
  { code: "LP-65", name: "Rubber Black", hex: "#303434" },
  { code: "TS-1", name: "Red Brown", hex: "#704537" },
  { code: "TS-2", name: "Dark Green", hex: "#2f4a38" },
  { code: "TS-3", name: "Dark Yellow", hex: "#9f894e" },
  { code: "TS-4", name: "German Grey", hex: "#45494b" },
  { code: "TS-5", name: "Olive Drab", hex: "#5a5b3f" },
  { code: "TS-6", name: "Matt Black", hex: "#191919" },
  { code: "TS-7", name: "Racing White", hex: "#e9e6db" },
  { code: "TS-8", name: "Italian Red", hex: "#b42c30" },
  { code: "TS-9", name: "British Green", hex: "#244c35" },
  { code: "TS-10", name: "French Blue", hex: "#3e77a9" },
  { code: "TS-11", name: "Maroon", hex: "#65333c" },
  { code: "TS-12", name: "Orange", hex: "#df6f25" },
  { code: "TS-14", name: "Black", hex: "#111111" },
  { code: "TS-15", name: "Blue", hex: "#214d8e" },
  { code: "TS-16", name: "Yellow", hex: "#e2c72e" },
  { code: "TS-17", name: "Gloss Aluminium", hex: "#b5b7b7" },
  { code: "TS-21", name: "Gold", hex: "#a88e48" },
  { code: "TS-22", name: "Light Green", hex: "#78a768" },
  { code: "TS-23", name: "Light Blue", hex: "#76a8c2" },
  { code: "TS-26", name: "Pure White", hex: "#f3f1e9" },
  { code: "TS-28", name: "Olive Drab 2", hex: "#67664b" },
  { code: "TS-29", name: "Semi Gloss Black", hex: "#222426" },
  { code: "TS-30", name: "Silver Leaf", hex: "#b5b8ba" },
  { code: "TS-34", name: "Camel Yellow", hex: "#c49236" },
  { code: "TS-35", name: "Park Green", hex: "#267752" },
  { code: "TS-38", name: "Gun Metal", hex: "#55595b" },
  { code: "TS-43", name: "Racing Green", hex: "#1f593e" },
  { code: "TS-44", name: "Brilliant Blue", hex: "#2e61a2" },
  { code: "TS-46", name: "Light Sand", hex: "#c5b17b" },
  { code: "TS-48", name: "Gunship Grey", hex: "#5a6063" },
  { code: "TS-49", name: "Bright Red", hex: "#c73436" },
  { code: "TS-50", name: "Mica Blue", hex: "#234f83" },
  { code: "TS-51", name: "Racing Blue", hex: "#254d83" },
  { code: "TS-52", name: "Candy Lime Green", hex: "#68a95a" },
  { code: "TS-55", name: "Dark Blue", hex: "#253c5e" },
  { code: "TS-56", name: "Brilliant Orange", hex: "#dd6826" },
  { code: "TS-61", name: "NATO Green", hex: "#4d5941" },
  { code: "TS-62", name: "NATO Brown", hex: "#5a4338" },
  { code: "TS-63", name: "NATO Black", hex: "#292d2c" },
  { code: "TS-66", name: "IJN Gray", hex: "#747d79" },
  { code: "TS-67", name: "IJN Gray Green", hex: "#90998a" },
  { code: "TS-68", name: "Wooden Deck Tan", hex: "#b49f75" },
  { code: "TS-69", name: "Linoleum Deck Brown", hex: "#7a4e3f" },
  { code: "TS-70", name: "Olive Drab", hex: "#57583e" },
  { code: "TS-80", name: "Flat Clear", hex: "#d5d5ce" },
  { code: "TS-82", name: "Rubber Black", hex: "#303434" },
  { code: "TS-83", name: "Metallic Silver", hex: "#b0b3b5" },
  { code: "TS-84", name: "Metallic Gold", hex: "#ae934a" },
  { code: "TS-86", name: "Pure Red", hex: "#b5232d" },
  { code: "TS-87", name: "Titanium Gold", hex: "#a8905e" },
  { code: "TS-88", name: "Titanium Silver", hex: "#a5a19a" },
];
